init:
  image:
    region: ${region}
eniConfig:
  create: true
  region: ${region}
  subnets:
    ${az_1}:
      id: ${subnet_1}
      securityGroups:
            - ${sg_node}
      
    ${az_2}:
      id: ${subnet_2}
      securityGroups:
            - ${sg_node}
      
    ${az_3}:
      id: ${subnet_3}
      securityGroups:
            - ${sg_node}
            
env:
  AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG: "true"
  ENI_CONFIG_LABEL_DEF: "topology.kubernetes.io/zone"

serviceAccount:
  create: false
  name: aws-node-terraform
